name: Create a Stage env


on:
    workflow_dispatch:
       inputs:
        PR_Number:
            description: 'Enter  PR number'
            required: true 




jobs:
    create-env:
        runs-on: ubuntu-latest
        steps:
            - name: Verify the given PR number
              uses: actions/github-script@v7
              id: verify_pr_number
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                result-encoding: string
                script: |
                   const response = await github.rest.pulls.get({
                    
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   pull_number: ${{ github.event.inputs.PR_Number}}
                   
                   
                   });

                   // check if PR number is valid or not

                    if (response.data.number !== ${{ github.event.inputs.PR_number }}) {
                    throw new Error('Pull request is not open or number is not valid!');
                     }
                    else {
                      console.log("PR number is valid with PR ref: " + response.data.head.ref);
                      return response.data.head.ref;
                      }


                    

