name: display file 

on:
 workflow_dispatch:

jobs:
    dispfile:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v2
            - name: display current directory
              run: pwd
            - name: display current directory files
              run: ls -lhrt
            - name: display file
              run: cat testfile
            #   working_directory: ./