name: strategy with multiple versions

on:
    workflow_dispatch: 

jobs:
    strat:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                py-versions: ["3.9","3.10","3.11"]
        steps:
            - name: Clone 
              uses: actions/checkout@v2
            - name: setup Python environment
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.py-versions }}
            - name: Display python version
              run: python --version